// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwWXhOXbrS_G3CTgEFghpJVYzTjUJAdOk',
    appId: '1:159527102703:web:e4bee8a73dc8fdbc80531a',
    messagingSenderId: '159527102703',
    projectId: 'elab-nepal',
    authDomain: 'elab-nepal.firebaseapp.com',
    storageBucket: 'elab-nepal.appspot.com',
    measurementId: 'G-1K5EBQJWT4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-wWlNhbkB8I7S8trdtSi6dQh-Aia-iWs',
    appId: '1:159527102703:android:65aae0237180b59480531a',
    messagingSenderId: '159527102703',
    projectId: 'elab-nepal',
    storageBucket: 'elab-nepal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJWKMzI7YIulEhCsY-fdHPIPZynXSKHqw',
    appId: '1:159527102703:ios:fce38dec648ea7ef80531a',
    messagingSenderId: '159527102703',
    projectId: 'elab-nepal',
    storageBucket: 'elab-nepal.appspot.com',
    androidClientId:
        '159527102703-s4j2q7fg8pgkq13v75apakv2d60rc59c.apps.googleusercontent.com',
    iosClientId:
        '159527102703-vegmr7ffd3don38pjbhkvoo0mhi8i8ei.apps.googleusercontent.com',
    iosBundleId: 'com.ktmrush.elab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJWKMzI7YIulEhCsY-fdHPIPZynXSKHqw',
    appId: '1:159527102703:ios:29789644e01c981f80531a',
    messagingSenderId: '159527102703',
    projectId: 'elab-nepal',
    storageBucket: 'elab-nepal.appspot.com',
    androidClientId:
        '159527102703-s4j2q7fg8pgkq13v75apakv2d60rc59c.apps.googleusercontent.com',
    iosClientId:
        '159527102703-h0iasfteskbolja1609d3dv5e0bess6c.apps.googleusercontent.com',
    iosBundleId: 'com.ktmrush.elab.RunnerTests',
  );
}
